### ISSUE TITLE
Demo Updates Needed

### ISSUE THREAD

**Issue by PCTipsGR** [NeotiDev/storm#1]
We need to update the demo link to demo.neotidev.com instead of .cf and also add a demo for giftrain.

**Comment by humbletyrant** [comment]
I'm going to work on this issue now.

**Comment by PCTipsGR** [comment]
> I'm going to work on this issue now.

Do you have by any chance access to neotidev.com DNS? Or could we just create a new folder in its repo and past demo there?

Thanks for working on this.

**Comment by PCTipsGR** [comment]
Actually demos are presented in https://demo.neotidev.com.
